// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSL.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TSL.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TSL.Core.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Escudo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Equipos_Nombre");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Ligas_Nombre");

                    b.ToTable("Ligas", (string)null);
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("int");

                    b.Property<byte>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<int>("TemporadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId")
                        .HasDatabaseName("IX_Partidos_EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId")
                        .HasDatabaseName("IX_Partidos_EquipoVisitanteId");

                    b.HasIndex("TemporadaId")
                        .HasDatabaseName("IX_Partidos_TemporadaId");

                    b.HasIndex("TemporadaId", "Jornada", "Fecha")
                        .HasDatabaseName("IX_Partidos_Temporada_Jornada_Fecha");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.PosicionEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Derrotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Empates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("GolesAFavor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GolesEnContra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PartidosJugados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TablaPosicionId")
                        .HasColumnType("int");

                    b.Property<int>("Victorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .HasDatabaseName("IX_PosicionesEquipos_EquipoId");

                    b.HasIndex("TablaPosicionId")
                        .HasDatabaseName("IX_PosicionesEquipos_TablaPosicionId");

                    b.HasIndex("TablaPosicionId", "EquipoId")
                        .IsUnique()
                        .HasDatabaseName("IX_PosicionesEquipos_Tabla_Equipo");

                    b.ToTable("PosicionesEquipos", (string)null);
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.TablaPosicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TemporadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId")
                        .IsUnique()
                        .HasDatabaseName("IX_TablasPosiciones_TemporadaId");

                    b.ToTable("TablasPosiciones", (string)null);
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Temporada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("LigaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LigaId")
                        .HasDatabaseName("IX_Temporadas_LigaId");

                    b.ToTable("Temporadas", (string)null);
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Partido", b =>
                {
                    b.HasOne("TSL.Core.Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Partidos_EquipoLocal");

                    b.HasOne("TSL.Core.Domain.Entities.Equipo", "EquipoVisitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Partidos_EquipoVisitante");

                    b.HasOne("TSL.Core.Domain.Entities.Temporada", "Temporada")
                        .WithMany("Partidos")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Partidos_Temporada");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.PosicionEquipo", b =>
                {
                    b.HasOne("TSL.Core.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Posiciones")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PosicionesEquipos_Equipo");

                    b.HasOne("TSL.Core.Domain.Entities.TablaPosicion", "TablaPosicion")
                        .WithMany("Posiciones")
                        .HasForeignKey("TablaPosicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PosicionesEquipos_TablaPosicion");

                    b.Navigation("Equipo");

                    b.Navigation("TablaPosicion");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.TablaPosicion", b =>
                {
                    b.HasOne("TSL.Core.Domain.Entities.Temporada", "Temporada")
                        .WithOne("TablaPosicion")
                        .HasForeignKey("TSL.Core.Domain.Entities.TablaPosicion", "TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TablasPosiciones_Temporada");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Temporada", b =>
                {
                    b.HasOne("TSL.Core.Domain.Entities.Liga", "Liga")
                        .WithMany("Temporadas")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Temporadas_Ligas");

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");

                    b.Navigation("Posiciones");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Liga", b =>
                {
                    b.Navigation("Temporadas");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.TablaPosicion", b =>
                {
                    b.Navigation("Posiciones");
                });

            modelBuilder.Entity("TSL.Core.Domain.Entities.Temporada", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("TablaPosicion");
                });
#pragma warning restore 612, 618
        }
    }
}
